### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by arshamsam** [mfkasim1/xcnn#1]
The 6-311++G(3df,3pd) basis for atomz 4 does not exist, but we will download it
Downloaded to /home/samazadi/dqc/dqc/api/.database/6-311ppg_3df_3pd_/04.gaussian94
Traceback (most recent call last):
  File "/home/samazadi/xcnn/xcdnn2/train.py", line 252, in <module>
    bestval = run_training(hparams)
  File "/home/samazadi/xcnn/xcdnn2/train.py", line 155, in run_training
    plsystem = LitDFTXC(hparams, entries)
  File "/home/samazadi/.local/lib/python3.9/site-packages/xcdnn2/litmodule.py", line 51, in __init__
    self.hparams = hparams
  File "/home/samazadi/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1178, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by mfkasim1** [comment]
What version of pytorch_lightning do you have? The library typically have not great backward compatibility

**Comment by arshamsam** [comment]
print(torch.__version__)
1.9.1+cu102

**Comment by arshamsam** [comment]
print(pytorch_lightning.__version__)
1.4.9

**Comment by mfkasim1** [comment]
Can you try using pytorch_lightning version 1.3.0?

**Comment by arshamsam** [comment]
print(pytorch_lightning.__version__)
1.3.0


Traceback (most recent call last):
  File "/home/samazadi/xcnn/xcdnn2/train.py", line 252, in <module>
    bestval = run_training(hparams)
  File "/home/samazadi/xcnn/xcdnn2/train.py", line 155, in run_training
    plsystem = LitDFTXC(hparams, entries)
  File "/home/samazadi/.local/lib/python3.9/site-packages/xcdnn2/litmodule.py", line 51, in __init__
    self.hparams = hparams
  File "/home/samazadi/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1178, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by mfkasim1** [comment]
How about older version of pytorch lightning?

**Comment by arshamsam** [comment]
seems working with version 1.0.0

**Comment by mfkasim1** [comment]
Great, I have specified the pytorch lightning version in the setup, so I can close this issue.
